# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac4a1184d8d73159c05211845c00fdabd6c37f48544d954d08cd718ff8c6d30416e6bc6dfde1804217c37b1e34e3fd3fabd22ee03ce0e524b6f6e6ed411a3300

test:
  secret_key_base: 201828a4222ad11a9ae42b43f13fb32c5316f312fb410cc0f6e6c9eac8e90b035d9da1aae5311ad69f908a7ce27dabb1a2e909e302b2c8f3b0e1589b07d3fde0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
